
DROP TABLE IF EXISTS app;
CREATE TABLE IF NOT EXISTS app (
	app_id numeric PRIMARY KEY,
	cem_code text NOT NULL,
	start_date date NOT NULL,
	state_code numeric,
	province_code numeric,
	district_code numeric,
	area numeric,
	action_code text,
	campaign numeric,
	oj_m numeric,
	oj_v numeric,
	op_m numeric,
	op_v numeric,
	os_m numeric,
	os_v numeric,
	aufr_m numeric,
	aufr_v numeric,
	aufl_m numeric,
	aufl_v numeric,
	auc_m numeric,
	auc_v numeric,
	ed_m numeric,
	ed_v numeric,
	es_m numeric,
	es_v numeric,
	esu_m numeric,
	esu_v numeric,
	pa_m numeric,
	pa_v numeric,
	lico_m numeric,
	lico_v numeric,
	fa_m numeric,
	fa_v numeric,
	pro_m numeric,
	pro_v numeric,
	col_m numeric,
	col_v numeric,
	sere_m numeric,
	sere_v numeric,
	fupu_m numeric,
	fupu_v numeric,
	fupri_m numeric,
	fupri_v numeric,
	emp_m numeric,
	emp_v numeric,
	gemp_m numeric,
	gemp_v numeric,
	trab_m numeric,
	trab_v numeric,
	cont_m numeric,
	cont_v numeric,
	per_m numeric,
	per_v numeric,
	osb_m numeric,
	osb_v numeric,
	mrc_m numeric,
	mrc_v numeric,
	rong_m numeric,
	rong_v numeric,
	mmcr_m numeric,
	mmcr_v numeric,
	ac_m numeric,
	ac_v numeric,
	po_m numeric,
	po_v numeric,
	ot_m numeric,
	ot_v numeric,
	inf_m numeric,
	inf_v numeric,
	nin_m numeric,
	nin_v numeric,
	adol_m numeric,
	adol_v numeric,
	adol_t_m numeric,
	adol_t_v numeric,
	jov_m numeric,
	jov_v numeric,
	adu_m numeric,
	adu_v numeric,
	may_m numeric,
	may_v numeric
);

DROP TABLE IF EXISTS CEM_MALE_VICTIM_DAYS;
CREATE TABLE IF NOT EXISTS CEM_MALE_VICTIM_DAYS (
	case_id numeric PRIMARY KEY,
	state_peru numeric NOT NULL,
	province_peru numeric NOT NULL,
	district_peru numeric NOT NULL,
	case_date date,
	physical_v_count numeric,
	sexual_v_count numeric,
	economical_v_count numeric,
	psychological_v_count numeric,
	first_time_count numeric,
	inf_count numeric,
	nin_count numeric,
	ado_count numeric,
	ado_t_count numeric,
	jov_count numeric,
	adu_count numeric,
	m60_count numeric,
	family_count numeric,
	love_count numeric,
	no_rel_count numeric,
	aggr_alcohol_count numeric,
	aggr_drug_count numeric,
	vict_disab_count numeric,
	vict_alco_count numeric,
	vict_drug_count numeric,
	vict_lgtbi_count numeric
);

DROP TABLE IF EXISTS CEM_FEMALE_VICTIM_DAYS;
CREATE TABLE IF NOT EXISTS CEM_FEMALE_VICTIM_DAYS (
	case_id numeric PRIMARY KEY,
	state_peru numeric NOT NULL,
	province_peru numeric NOT NULL,
	district_peru numeric NOT NULL,
	case_date date,
	physical_v_count numeric,
	sexual_v_count numeric,
	economical_v_count numeric,
	psychological_v_count numeric,
	first_time_count numeric,
	inf_count numeric,
	nin_count numeric,
	ado_count numeric,
	ado_t_count numeric,
	jov_count numeric,
	adu_count numeric,
	m60_count numeric,
	family_count numeric,
	love_count numeric,
	no_rel_count numeric,
	aggr_alcohol_count numeric,
	aggr_drug_count numeric,
	vict_disab_count numeric,
	vict_alco_count numeric,
	vict_drug_count numeric,
	vict_lgtbi_count numeric
);

DROP TABLE IF EXISTS WEEK_DATE;
CREATE TABLE IF NOT EXISTS WEEK_DATE (
   week_id numeric PRIMARY KEY,
   date_start date NOT NULL,
   date_end date NOT NULL
);

DROP TABLE IF EXISTS CEM_FEMALE_VICTIM_WEEKS;
CREATE TABLE IF NOT EXISTS CEM_FEMALE_VICTIM_WEEKS (
	case_id numeric PRIMARY KEY,
	state_peru numeric NOT NULL,
	province_peru numeric NOT NULL,
	district_peru numeric NOT NULL,
	week numeric,
	physical_v_count numeric,
	sexual_v_count numeric,
	economical_v_count numeric,
	psychological_v_count numeric,
	first_time_count numeric,
	inf_count numeric,
	nin_count numeric,
	ado_count numeric,
	ado_t_count numeric,
	jov_count numeric,
	adu_count numeric,
	m60_count numeric,
	family_count numeric,
	love_count numeric,
	no_rel_count numeric,
	aggr_alcohol_count numeric,
	aggr_drug_count numeric,
	vict_disab_count numeric,
	vict_alco_count numeric,
	vict_drug_count numeric,
	vict_lgtbi_count numeric
);

DROP TABLE IF EXISTS CEM_MALE_VICTIM_WEEKS;
CREATE TABLE IF NOT EXISTS CEM_MALE_VICTIM_WEEKS (
	case_id numeric PRIMARY KEY,
	state_peru numeric NOT NULL,
	province_peru numeric NOT NULL,
	district_peru numeric NOT NULL,
	week numeric,
	physical_v_count numeric,
	sexual_v_count numeric,
	economical_v_count numeric,
	psychological_v_count numeric,
	first_time_count numeric,
	inf_count numeric,
	nin_count numeric,
	ado_count numeric,
	ado_t_count numeric,
	jov_count numeric,
	adu_count numeric,
	m60_count numeric,
	family_count numeric,
	love_count numeric,
	no_rel_count numeric,
	aggr_alcohol_count numeric,
	aggr_drug_count numeric,
	vict_disab_count numeric,
	vict_alco_count numeric,
	vict_drug_count numeric,
	vict_lgtbi_count numeric
);